### ISSUE TITLE
[Request] Bundle yarn or specific version in package.json

### ISSUE THREAD

**Issue by SettingDust** [blacksmithgu/datacore#15]
Seems my yarn 3 break the lock file when import the project

**Comment by GNRSN** [comment]
I think the current lockfile was generated with Yarn classic (v1), not Berry (v2/v3).

**Comment by SettingDust** [comment]
> I think the current lockfile was generated with Yarn classic (v1), not Berry (v2/v3).

ya

**Comment by GNRSN** [comment]
It's not really possible to "bundle" a package-manager with a repo. [Corepack](https://nodejs.org/dist/latest-v20.x/docs/api/corepack.html) will adress this but it's still in an experimental stage the requires opt-in so it's not really feasible for real use as you can't expect developers to have it enabled. 

The established "solution" OSS is afaik to document the package-manager used under the `contributing` section of the `readme.md`.

**Comment by SettingDust** [comment]
> It's not really possible to "bundle" a package-manager with a repo. [Corepack](https://nodejs.org/dist/latest-v20.x/docs/api/corepack.html) will adress this but it's still in an experimental stage the requires opt-in so it's not really feasible for real use as you can't expect developers to have it enabled.
> 
> The established "solution" OSS is afaik to document the package-manager used under the `contributing` section of the `readme.md`.

False.
https://yarnpkg.com/features/zero-installs

**Comment by mProjectsCode** [comment]
Why do something like this? Every package manager should work, no? 

And if another package manager changes the `package-lock.json`, just don't include the changes in the commit.

**Comment by SettingDust** [comment]
> Why do something like this? Every package manager should work, no? 
> 
> And if another package manager changes the `package-lock.json`, just don't include the changes in the commit.

no, mess package manager will mess peer packages and lock. In some situation package url will different with the same package manifest.

**Comment by GNRSN** [comment]
> False. https://yarnpkg.com/features/zero-installs

I stand corrected, however that's a "feature" of Yarn Berry that also requires the PnP feature of Yarn Berry to be utilised.

**Comment by SettingDust** [comment]
> > False. [yarnpkg.com/features/zero-installs](https://yarnpkg.com/features/zero-installs)
> 
> I stand corrected, however that's a "feature" of Yarn Berry that also requires the PnP feature of Yarn Berry to be utilised.

Noop. It's a feature of yarn. And don't need pnp
