### ISSUE TITLE
How can I used it in obsidian after installation ?

### ISSUE THREAD

**Issue by amatya-aditya** [blacksmithgu/datacore#19]
basically title.

**Comment by xDovos** [comment]
it isn't released yet so you can't. (you can still install it if you know how to convert the .ts into the right main.js plugin stuff but that isn't really helpful too because most of the query stuff is still missing)

**Comment by kickTiger** [comment]
> it isn't released yet so you can't. (you can still install it if you know how to convert the .ts into the right main.js plugin stuff but that isn't really helpful too because most of the query stuff is still missing)

I have successfully compiled and installed the plugin, but I am unsure of how to utilize it. Unfortunately, I cannot locate the corresponding command in the command palette. 

Would you kindly provide me with instructions on how to use this plugin, even if it is just for a partial feature? Your guidance would be greatly appreciated.

**Comment by mProjectsCode** [comment]
@kickTiger see the comment above. Currently, the plugin only does behind-the-scenes work and there is no way yet to interact with the plugin. In short: There is not functionality that you can use yet.

**Comment by kickTiger** [comment]
@mProjectsCode Thank you for your response. I installed it and saw the settings interface, I thought it already had a UI to use.

**Comment by tyf2018** [comment]
I manually installed version 0.16 today and tried it out, but I couldn't find a successful way to run DataCore.
