### ISSUE TITLE
Full text search? Block level querying?

### ISSUE THREAD

**Issue by TfTHacker** [blacksmithgu/datacore#2]
Exciting project. Will this project include any concept of full-text search, or better yet, the ability to do searches at a block level?

The work you have done with dataview is inspiring and took a lot of time and energy. Not sure there is any true way of expressing gratitude for it.

**Comment by blacksmithgu** [comment]
I haven't committed to full-text search yet, but I'm going to experiment with how heavy of a memory burden a simple inverted-word index is going to be, so at least word-level search may be possible.

Block-level search will be possible on tags and fields at the very least; if the word query works out then word queries at block level will also work.

**Comment by blacksmithgu** [comment]
I am looking into Obsidian-style search as well, which will either try to use Obsidian's search functionality to find files, or which will trade off arbitrary text search for slower queries (if you use text search).

**Comment by TfTHacker** [comment]
you have ambitious goals :-) but really amazing tool. having some kind of solid database under the hood that we can all build on is a real gift. Thank you.
