### ISSUE TITLE
Feature request for querying markdown table

### ISSUE THREAD

**Issue by ReactiveMatter** [blacksmithgu/datacore#22]
Since the aim of datacore is to give notion like feel to Obsidian, my concern is for small databases creating folder based setup with one file for each entry is little time taking. It also results in unnecessary increase in number of files in vault without adding much value.

It would be a great addition to datacore if it can query markdown tables (using table id), and if possible edit, add and delete the content. That way one table will be one database.

**Comment by blacksmithgu** [comment]
I'm not targeting adding this specific functionality right now, but this does sound like a good idea! I am looking at support for "inline data", where the actual data for a given view is stored inside the `datacore` block directly as plain YAML, which may work as an interim solution until something like markdown table parsing is implemented.

**Comment by AdamsGH** [comment]
+1 for this feature, it whould be amazing if you can implement such

**Comment by Friedolito** [comment]
+1 that would be really great :)

**Comment by blacksmithgu** [comment]
This functionality is supported via blocks tagged `yaml:data`. They will show up as datablocks which can be searched for like any other datacore construct.

**Comment by blacksmithgu** [comment]
(Documentation incoming)

**Comment by ReactiveMatter** [comment]
Great. Thank you for considering this.
