### ISSUE TITLE
Is it possible to use this plugin in obsidian ? 

### ISSUE THREAD

**Issue by amatya-aditya** [blacksmithgu/datacore#36]
It would be great. Eagerly waiting for this.

**Comment by GamerGirlandCo** [comment]
> It would be great. Eagerly waiting for this.

it is, if you open up the console and/or know how to use the react API (in codeblocks) :)

**Comment by HananoshikaYomaru** [comment]
@GamerGirlandCo  the last release is in June. What happens to this project or the focus has been switched back to dataview again?

**Comment by xDovos** [comment]
@HananoshikaYomaru you need to look at the commits and not release. The last commit was a month ago and Christmas time is normally not a time where people have much time to do their hobby.

**Comment by amatya-aditya** [comment]
I've been curious about the release date of this plugin to the public, as we're enthusiastic about trying it out and providing our feedback. The database feature plugin is the sole reason holding me back from fully embracing Obsidian. Once it's available, I'll transition from Notion.

**Comment by 23426356587** [comment]
Is there an update for this question?

**Comment by blacksmithgu** [comment]
It's presently in power-user mode - the index is available and JSX views work, though it's all coding-based still. I recommend lurking in the Discord linked in the README in the "Contributing" section if you want to see progress towards general availability.

I'll probably be communiating broadly when the plugin is GA'd.
