### ISSUE TITLE
Will DataviewJS Scripts be compatible with Datacore?

### ISSUE THREAD

**Issue by YousufSSyed** [blacksmithgu/datacore#4]
I just started looking at Dataview today and neither repo nor the documentation site for it mentions Datacore. I spent a few hours figuring out how to use Dataview and couldn't due to poor documentation. I wished I had known about Datacore and wait for that to come out. **DataCore should be mentioned in both places for the sake of new users.**

Also, when would documentation for Datacore come out?

**Comment by blacksmithgu** [comment]
I'll announce datacore once it is in a usable state that has near feature parity with Dataview; it's still very much in the work-in-progress stage and is not ready to be used. Documentation will be released along side features in datacore as they are added.

I haven't made a decision on whether DataviewJS scripts will be fully compatible or not yet - there may be a legacy emulation mode which will support DataviewJS scripts, but the datacore scripting API is moderately different for performance reasons to make it harder for scripts to accidentally crash the vault.

**Comment by YousufSSyed** [comment]
I really like the capabilities of Dataview and would like to write DataviewJS scripts of my own. Would you recommend me to wait until datacore is out or go ahead and write them? If I should wait, then when would you estimate documentation to come out and be comprehensive in relation to when datacore would be ready?

**Comment by blacksmithgu** [comment]
If you are familiar with JavaScript, simple DataviewJS scripts are straightforward to write and use. The skill set will be transferable to DatacoreJS.

**Comment by YousufSSyed** [comment]
Well, I looked at the DataviewJS documentation and there are a lot of things missing so I had trouble with making scripts. And I don't think it makes sense to spend time improving documentation for DataviewJS when DataCore seems to be right around the corner. Idk when it's coming, but as of now on the readme page it says "expect to see early releases available in Obsidian in late January 2023!" 

So back to my question:
> Would you recommend me to wait until DataCore is out or go ahead and write them? If I should wait, then when would you estimate documentation to come out and be comprehensive in relation to when DataCore would be ready?

**Comment by blacksmithgu** [comment]
If you are unsure about Dataview's documentation, then just wait for the Datacore scripting API. It will come with TSDoc comments/docs in the style of most libraries.

**Comment by alancunha26** [comment]
Datacore will have inline fields or it will focus in native frontmatter?

**Comment by imeed166** [comment]
@alancunha26 you can check this issue #3, it answers your question.

**Comment by YousufSSyed** [comment]
@alancunha26 You and anyone who reads this should consider making separate issues.
