### ISSUE TITLE
Thank you and how may we help

### ISSUE THREAD

**Issue by simonfossom** [blacksmithgu/datacore#43]
I just wanted to leave a message of support since a year is closing in since last release.

So many people benefit from your work. We all appriciate it very much.

Dataview transform Obsidian. It's default for almost every setup I've seen. I can't imagine using Obsidian without it.

When you announced DataCore it got community very excited. But I can imagine the complexity of the project making the development progress very slow. 

If we as community can help anyhow please let us know how to support your awesome work.

**Comment by blacksmithgu** [comment]
Thanks for the kind words! In truth, I've had a fairly tumultuous year at work and I only had scraps of time here and there to keep chipping away at datacore. What I have is very nearly usable but is missing some final UI elements to become complete.

I've recently come back now that I have a bit of breathing room and am trying to surge to get Datacore spinning - I've finally started a (tremendously basic) Discord for it here: https://discord.gg/YbjpdMZ9.

**Comment by m-smith** [comment]
Hey, I'm getting an issue when I try to follow the link saying it has expired.

**Comment by xDovos** [comment]
@m-smith try the one in the readme.
