### ISSUE TITLE
[Bug(?)] Non-JS Datacore Queries Not Rendering

### ISSUE THREAD

**Issue by julroger2013** [blacksmithgu/datacore#45]
It looked like, from the documentation, that the "vanilla" datacore query block (equivalent to a \`\`\`dataview code block) would have \`\`\`datacore as the right way to start the code block.

Is that right?

I'm finding that the following code block doesn't render anything:

\`\`\`datacore
@pages
\`\`\`

Apologies if I misunderstood the documentation or this function just isn't part of the beta yet. Figured it couldn't hurt to ask.

**Comment by Quorafind** [comment]
Currently, `datacore` codeblock is not supported yet. Hovever, you can use code below to render pages:

````
```datacorets  
return dc.api.query("@page and #game").map((i)=> "- " + i.$file)
```
````

**Comment by blacksmithgu** [comment]
Non JS views aren't available yet since I haven't really figured out how they should look like; I recommend the datacorejs/datacorejsx blocks for now.

**Comment by julroger2013** [comment]
That makes sense.

I have time on my hands for at least a couple months. I don't have the coding skill to pitch in, but I could probably write some documentation if that would be useful. All ears if you can use any help.

**Comment by blacksmithgu** [comment]
If you're interested in contributing or trying out the plugin I'd recommend joining/lurking in the discord (link is in the contributing section in the README) - happy to iterate there. The current (lacking) documentation is here: https://github.com/blacksmithgu/datacore/tree/master/docs.
