### ISSUE TITLE
[Feature Request] Wildcards (or even regeexp?) in useQuery("#tags")

### ISSUE THREAD

**Issue by jeetsukumaran** [blacksmithgu/datacore#64]
Would it be possible to support some way querying for tag patterns rather than the fully specified tags?

This would support tag multihierarchical taxonomies where it might be useful to query some common leaf terms across hierarchies (e.g., ``#resource/visual/local", "#resource/visual/link", "#resource/audio/link", "#concept/{{topic}}/definition", "#concept/{{topic}}/support" etc. ) 

E.g. regexp
```
@section and `#concept/.*/definition$`
```

or otherwise something glob-like/simpler:
```
@section and #concept and #*definition*
@section and #concept/*/definition
```

**Comment by GamerGirlandCo** [comment]
great suggestion! should be relatively easy to implement i think :)

**Comment by GamerGirlandCo** [comment]
UPDATE:

it's already been implemented lol

https://github.com/blacksmithgu/datacore/blob/e8919f6748008a69f47914d9db3e13efda4331ce/src/expression/functions.ts#L526-L531

syntax would be something like:

`@section and any($tags, (it) => regextest(it, "#concept/.*/definition$))`.

let me know if it works :)

**Comment by jeetsukumaran** [comment]
Fantastic! It works really well, thank you :)
