### ISSUE TITLE
Can you provide some UI preview images for Datacore?

### ISSUE THREAD

**Issue by kickTiger** [blacksmithgu/datacore#9]
I am immensely grateful for the plugin developed by the author which has been of great assistance to me. 

I have been closely monitoring the new developments on Datacore and I was wondering if the author could provide some insights into the user interface and operations. I would like to feature Datacore in one of my articles, therefore your kind assistance is greatly appreciated. 

Thank you once again for your hard work. It would be great if some screenshots of the user interface are also available.

**Comment by Krakor92** [comment]
Just like Dovos said in another issue:
> Let the man write the plugin [...]

I'm not familiar with how Obsidian plugins are developed but judging from Dataview's folder structure, I'm pretty confident in saying that Datacore's UI hasn't been done don't have any `ui` made at that point (or at least it's not pushed in the repository)

**Comment by Krakor92** [comment]
Just like Dovos said in another issue:
> Let the man write the plugin [...]

I'm not familiar with how Obsidian plugins are developed, but judging by [Dataview's folder structure](https://github.com/blacksmithgu/obsidian-dataview/tree/master/src), I'm fairly confident in saying that Datacore's UI hasn't been done yet.

**Comment by GamerGirlandCo** [comment]
![image](https://github.com/blacksmithgu/datacore/assets/37163052/1f3103d8-9af0-4c31-9770-93f64198269d)

here's what the table view looks like :)

**Comment by blacksmithgu** [comment]
Here's a random snippet of the view I use for showing my played games:

<img width="1517" alt="image" src="https://github.com/blacksmithgu/datacore/assets/616490/64cadb73-8112-42e1-9f7a-1f628050601a">
